version: "3.8"
services:
  space-marine-frontend:
    container_name: space-marine-frontend
    image: davidpj/space-marine-frontend
    build: ./frontend
    ports:
    - published: 5000
      target: 5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
  space-marine-role:
    container_name: space-marine-role
    image: davidpj/space-marine-role
    build: ./role
  space-marinechapter:
    container-name: space-marine-chapter
    image: davidpj/space-marine-chapter
    build: ./chapter
  space-marine-name:
    container_name: space-marine-name
    image: davidpj/space-marine-name
    build: ./name
