version: "3.7"
services:
  frontend:
    container_name: space-marine-frontend
    image: davidpj/space-marine-frontend
    build: ./frontend
    ports:
    - published: 5000
      target: 5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
  role:
    container_name: space-marine-role
    image: davidpj/space-marine-role
    build: ./role
  chapter:
    container_name: space-marine-chapter
    image: davidpj/space-marine-chapter
    build: ./chapter
  name:
    container_name: space-marine-name
    image: davidpj/space-marine-name
    build: ./name
