# tasks file for nginx

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  register: nignx_time

- name: check install
  debug:
    msg: "{{ nginx_time }}"

- name: Start nginx
  service:
    name: nginx
    state: started
 
- name: Copy nginx file over
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config
  
- name: check copy
  debug:
    msg: "{{ nginx_config }}"

- name: Restart nginx 
  service:
    name: nginx
    state: restarted
  when: nginx_config.changed == true