---
# tasks file for swarm_worker- 
- name: Add worker
  docker_swarm:
    state: join
    join_token: "{{ hostvars['swarm-manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarm-manager:2377' ]